### ISSUE TITLE
ngModel directive does not work

### ISSUE THREAD

**Issue by zsolt-racz** [EddyVerbruggen/nativescript-numeric-keyboard#11]
I'm trying to utilize this plugin in NativeScript 3.0 using Angular4, but I keep getting the following errors when using the _ngModel_ directive:
```
JS: ERROR Error: Uncaught (in promise): Error: No value accessor for form control with unspecified name attribute
JS: Error: No value accessor for form control with unspecified name attribute
```

My code looks like this:
`<NumericKeyboard (returnPress)="checkCode($event)" [(ngModel)]="code" hint="{{'ticket_code'|translate}}" autocorrect="false" autocapitalizationType="none" keyboardType="number" returnKeyType="go"></NumericKeyboard>`

Is it even supposed to work? Without the _ngModel_ directive the errors disappear.

**Comment by EddyVerbruggen** [comment]
I'm not sure as I haven't used it with `ngModel`.

This is how I use it (abbreviated):

```html
<NumericKeyboard (textChange)="pinFieldChanged($event)" [text]="pincode"></NumericKeyboard>
```

```typescript
  pinFieldChanged(args: PropertyChangeData): void {
    let input = args.value;
  }
```
