### ISSUE TITLE
App crashes when running it in release mode using this plugin (nativescript-numeric-keyboard) in IOS

### ISSUE THREAD

**Issue by macin40** [EddyVerbruggen/nativescript-numeric-keyboard#12]
`JS ERROR ReferenceError: Can't find variable: MMNumberKeyboardDelegate`
App crashes when in release mode using this plugin, and the above error is encountered when running through xcode.

**Comment by EddyVerbruggen** [comment]
Please share a repo reproducing this issue - I'm using it in a production app without issues.

**Comment by macin40** [comment]
@EddyVerbruggen I cannot share the repo because it is confidential .

**Comment by EddyVerbruggen** [comment]
OK. Please reopen when you have a small repo reproducing the issue.

**Comment by macin40** [comment]
![screen shot 2017-07-13 at 7 03 39 pm](https://user-images.githubusercontent.com/22330484/28169589-7b68c2c6-6800-11e7-9565-80d332d0f86e.png)
