### ISSUE TITLE
App crashes when running it in release mode using this plugin (nativescript-numeric-keyboard) in IOS

### ISSUE THREAD

**Issue by macin40** [EddyVerbruggen/nativescript-numeric-keyboard#14]
`JS ERROR ReferenceError: Can't find variable: MMNumberKeyboardDelegate`
App crashes when in release mode using this plugin, and the above error is encountered when running through xcode.
![screen shot 2017-07-13 at 7 03 39 pm](https://user-images.githubusercontent.com/22330484/28169805-0ec90cce-6801-11e7-9888-dd968d0d30d5.png)

**Comment by mrkorsar** [comment]
+1 I have the same problem, when i tried to compile app in xcode i get error "Directory not found for option '-F/Users/<my apple id>/Library/Developer/Xcode/DerivedData/<project>/Build/Products/Debug-iphoneos/MMNumericKeyboard'"

In emulator i have no problem (tns run ios --emulator)

**Comment by EddyVerbruggen** [comment]
Make sure you're running the latest Xcode version, `rm -rf platforms/ios`, and run again.
