### ISSUE TITLE
Button color

### ISSUE THREAD

**Issue by dpdragnev** [EddyVerbruggen/nativescript-numeric-keyboard#15]
First off, great plugin.  Thanks for taking the time to make it.
This is more of a question than an issue.

Is there a way to change the background color of the Done button?

Thank you.

**Comment by EddyVerbruggen** [comment]
Hi @dpdragnev, thanks!

It's not currently possible but I can take a look. Can you perhaps share with me a little drawing or manipulated screenshot of what you want to achieve, so I'm sure we're on the same page?

**Comment by dpdragnev** [comment]
Thank you @EddyVerbruggen for the quick response.  I am referring to background color of the button indicated by the green arrow.  My design team wanted me to try to match the color scheme of the app.  This is not a deal breaker.  I was just wondering if it was possible.

![20170920_095626](https://user-images.githubusercontent.com/11344576/30656897-785f1768-9dea-11e7-83fb-244795dcec1f.jpg)

**Comment by EddyVerbruggen** [comment]
Oh, sorry, makes sense. I'm using a modified native library for this plugin and I think this could be something that can be added.

Note to self, it's probably [this line](https://github.com/matmartinez/MMNumberKeyboard/blob/master/Classes/MMNumberKeyboard.m#L754) we need to expose.

**Comment by dpdragnev** [comment]
Thank you :)

**Comment by marcellomorellato** [comment]
is there any updates for the "done button color" ?  it would be a very useful feature. thanks

**Comment by EddyVerbruggen** [comment]
It turns out to be pretty hard to "hack" this into the iOS lib we're using, so no update yet.

**Comment by EddyVerbruggen** [comment]
OK, figured it out while I was updating the plugin for NativeScript 5 (rc) compatibility. This is now available as shown in the demo and docs. Look for `returnKeyButtonBackgroundColor`.
