### ISSUE TITLE
Text always left align when input done

### ISSUE THREAD

**Issue by luckyxhu** [EddyVerbruggen/nativescript-numeric-keyboard#16]
I have set the text-align to right, initial is fine, but when input is finish and lost focus, the text become left aligned. this is only iOS behavior, android has no problem.

**Comment by EddyVerbruggen** [comment]
Yeah I noticed the same, not sure what causes it. Ideas?

**Comment by EddyVerbruggen** [comment]
This took me long enough to fix. Well actually, it's some limitation in the framework that I had to work around.

I found that fixing this issue with `TextView` was not possible, but switching to (what I wanted to use in the first place) a `TextField` makes the issue go away.

However, that meant I had to fix the issue I experienced in the first place: the `textChange` event not firing when a button was pressed. But I've hacked my way around that.

The `TextView` ➡️`TextField` change means a major version bump as when using `decorate()` it will break your app (although it's a very easy fix).
