### ISSUE TITLE
Nativescript 5.0 crash

### ISSUE THREAD

**Issue by closca** [EddyVerbruggen/nativescript-numeric-keyboard#22]
Hi, I have upgraded to Nativescript 5.0 and I get this:
`TypeError: undefined is not an object (evaluating 'this.nativeView.inputView = this._keyboard')`

I have edited in node_modules/nativescript-numeric-keyboard/numeric-keyboard.ios.js line 107:
```
if(this.nativeView) {
        this.nativeView.inputView = this._keyboard;
 }
```
I no longer get the error, but I have the normal keyboard.

**Comment by JamesRoome** [comment]
Also having this issue with 5.0. @closca Thanks for the workaround!

**Comment by JamesRoome** [comment]
I updated to the newest version 4.2.0 and the error went away on iOS.
