### ISSUE TITLE
Error building for Android with AOT checked.

### ISSUE THREAD

**Issue by relez** [EddyVerbruggen/nativescript-numeric-keyboard#23]
Hi there, I am trying to compile my app using Webpack, Uglify, Snapshot and AOT for Android and it fails when its trying to compile the project.
This is the error message:

`'NSNUMKEY_DIRECTIVES' is not initialized at nativescript-numeric-keyboard/angular/index.ts(1,14)`

 If I uncheck AOT it works.

Is it compatible with AOT for Android?

Thanks!

**Comment by EddyVerbruggen** [comment]
Hi!

I'm using this in an iOS app with AOT and that's all fine, but I'd be happy to try it on Android.. so can you provide me with a repo I can test with?

**Comment by relez** [comment]
Hi Eddy, sorry about the inconveniences, I was not using webpack before and I was using this way to add the plugin in my module:

```
import { NSNUMKEY_DIRECTIVES } from "nativescript-numeric-keyboard/angular";
 
declarations: [
  NSNUMKEY_DIRECTIVES,
]
```

I did not remember I had to change to this:

```
import { registerElement } from "nativescript-angular";
registerElement("NumericKeyboard", () => require("nativescript-numeric-keyboard").NumericKeyboardView);
```

Now its working as expected!

Thanks!

**Comment by EddyVerbruggen** [comment]
Happy to hear that, thanks for the update!
