### ISSUE TITLE
Register element for use with {N} Vuejs

### ISSUE THREAD

**Issue by KoenPaas** [EddyVerbruggen/nativescript-numeric-keyboard#25]
Request for documentation on how to register element using vuejs.

**Comment by EddyVerbruggen** [comment]
Will do, but to get you going:

Here's how you register it: https://github.com/EddyVerbruggen/footplr/blob/3cea34a97a11726d6bd23252b79808ea35bb05ee/app/main.ts#L16

And this is how you can use it: https://github.com/EddyVerbruggen/footplr/blob/3cea34a97a11726d6bd23252b79808ea35bb05ee/app/pages/home/components/measurements/measurement-entry/exercise/components/NumberInput.vue#L2

**Comment by EddyVerbruggen** [comment]
Updated the readme as well: https://github.com/EddyVerbruggen/nativescript-numeric-keyboard/tree/85c2160683184fc8dd1fc589260974d98cdcccd9#usage-with-vue

**Comment by KoenPaas** [comment]
You're the man! Ga zo door.

**Comment by KoenPaas** [comment]
Is there anyway of using v-model? Doesn't seem to be working.

**Comment by EddyVerbruggen** [comment]
I noticed the same and didn't bother to investigate, but simply used `this.$refs` as in the example mentioned above. Will that work for you?

**Comment by KoenPaas** [comment]
Yeah i got it working using the following.

`<NumericKeyboard ref="input" @textChange="setAmount" locale="nl_NL" />`

`setAmount() {
            let value = this.$refs.input.nativeView.text
            this.amount = value
        },`
