### ISSUE TITLE
multiple textfields: onReturnKeyPressed callback and textChange event work only for last created instance

### ISSUE THREAD

**Issue by Roman86** [EddyVerbruggen/nativescript-numeric-keyboard#27]
```
function onTextChange(args: EventData) {
    const t = <TextField>args.object;
    console.log("text entered: " + t.text);
}

function setupNumInput(inp: TextField) {

    inp.on("textChange", onTextChange);
    // EVENTS DON'T WORK WITH MULTIPLE INPUTS! ONLY THE LAST ONE IS WORKING!
    new NumericKeyboard().decorate({
        textField: inp,
        returnKeyTitle: "OK",
        returnKeyButtonBackgroundColor: new Color("#4b7786"),
        locale: "en_US", // or "nl_NL", or any valid locale really (to define the decimal char)
        noDecimals: false,
        noIpadInputBar: true, // suppress the bar with buttons iOS renders on iPad since iOS 9
        onReturnKeyPressed() {
            console.log("RETURN!", inp);

            return true;
        }
    });
    console.log("setup", inp);
}
```

if I call `setupNumInput` on multiple textfields - I see console output that all of them were successfully initialized. But other console output ("RETURN!" and "text entered") is only works for the last (in order of initialization) text field. Other text fields look fine, but no events nor callbacks being invoked.

I've already found a solution, will prepare a pull request shortly

**Comment by EddyVerbruggen** [comment]
Ha, great catch! I've never tested with more than one decorated textfield so never saw this issue.

**Comment by Roman86** [comment]
thanks for a super-fast merge! Looking forward for a new NPM release ;)

**Comment by EddyVerbruggen** [comment]
You're welcome! I'll be testing this a little and release one tomorrow 👍
