### ISSUE TITLE
Using returnPress event on html attribute (Angular)

### ISSUE THREAD

**Issue by alonstar** [EddyVerbruggen/nativescript-numeric-keyboard#31]
How do I add event using html attribute? I used (returnPress) is not wokring, also onReturnKeyPressed or returnKeyPressed.

- tns-core-modules v5.3.1
- nativescript-numeric-keyboard v4.2.3 
- nativescript-angular v7.2.3

`
<NumericKeyboard col="1" class="no-border text-right font-size-14" returnKeyType='done' (returnPress)="goEstimate($event)" [(ngModel)]="stockInfo.closePrice" maxLength="10"></NumericKeyboard>
`

And I tried to add value accessor for numeric keyboard for someone like to use ngModel tag.

`

    import { Directive, forwardRef } from '@angular/core';
    import { NG_VALUE_ACCESSOR } from '@angular/forms';

    import { TextValueAccessor } from 'nativescript-angular/forms/value-accessors/text-value-accessor';

    const MASKED_TEXT_VALUE_ACCESSOR = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => NumericKeyboardValueAccessor),
    multi: true
    };

    @Directive({
    // tslint:disable-next-line:directive-selector
    selector: 'NumericKeyboard[ngModel], NumericKeyboard[formControlName], NumericKeyboard[formControl]',
    providers: [MASKED_TEXT_VALUE_ACCESSOR],
    host: {
        '(blur)': 'onTouched()',
        '(textChange)': 'onChange($event.value)'
    },
    })
    // tslint:disable-next-line:directive-class-suffix
    export class NumericKeyboardValueAccessor extends TextValueAccessor {
    }
`

**Comment by EddyVerbruggen** [comment]
Good point. Check out 4.3.0 (now on npm).

**Comment by alonstar** [comment]
hi,
Thanks very mush ! but it only works on iOS,  could you fix it on andorid ?

**Comment by EddyVerbruggen** [comment]
On Android this plugin doesn't replace the keyboard..
