### ISSUE TITLE
Can't change returnKeyButtonBackgroundColor value when Keyboard is open.

### ISSUE THREAD

**Issue by Sauvetonbio** [EddyVerbruggen/nativescript-numeric-keyboard#37]
Hello, we are using Nativescript-vue.
We would like use a new color when text entered by user is valid.

```
<NumericKeyboard :returnKeyButtonBackgroundColor="color"> </NumericKeyboard>

//initial
this.color = "black"

//after validation
this.color = "green"
```

Could you please help us about this ? 
Thank you Eddy, all your plugins are usefull for us :)

**Comment by EddyVerbruggen** [comment]
Hi! I'm sorry but I don't think the native component used supports doing that.
